name: Lint and Test Charts
on:
  pull_request:
    paths:
      - "charts/**"
      - '!**.md'
jobs:
  lint-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # 2.8.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # 1.14.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: kindest/node:v1.35.1@sha256:b08d1f9b5244fb2aae7bea9861c1d372a9535f259efed62a9e92e6b5ab500529
          version: v0.31.0
      - name: Apply cert-manager
        run: |
          CERT_MANAGER_VERSION=$(grep '^CERT_MANAGER_VERSION' Makefile.versions | awk '{print $3}')
          CERT_MANAGER_CHECKSUM=$(grep '^CERT_MANAGER_CHECKSUM' Makefile.versions | awk '{print $3}')
          curl -fsSL "https://github.com/cert-manager/cert-manager/releases/download/v${CERT_MANAGER_VERSION}/cert-manager.yaml" -o cert-manager.yaml
          echo "${CERT_MANAGER_CHECKSUM}  cert-manager.yaml" | sha256sum -c -
          kubectl apply -f cert-manager.yaml
          kubectl -n cert-manager wait --for=condition=available --timeout=180s --all deployments
      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
